### ISSUE TITLE
C++ version

### ISSUE THREAD

**Issue by Raiden-Makoto** [jo3-l/cp-practice#2]
Use C++17 nor C++14 noob and stop using Java

**Comment by PNGNS-Marekos1111** [comment]
Also can I contribute

**Comment by jo3-l** [comment]
https://github.com/jo3-l/cp-practice/tree/main/src/main/cpp -- all my newer solutions (after ~August 2021) are in C++ 14. The Java solutions are leftover from before that.

Re: whether you can contribute -- if you see a typo or something feel free to fix but for the most part I'd like to not make this a place to store other peoples' solutions.

**Comment by Raiden-Makoto** [comment]
K boomer
